export const PRODUCTS_GET_ALL = 'PRODUCTS_GET_ALL'
export const PRODUCTS_GET_ALL_F = 'PRODUCTS_GET_ALL_F'
export const PRODUCTS_GET_ALL_R = 'PRODUCTS_GET_ALL_R'

export const PRODUCTS_GET_ALL_FILTER = 'PRODUCTS_GET_ALL_FILTER'
export const PRODUCTS_GET_ALL_FILTER_F = 'PRODUCTS_GET_ALL_FILTER_F'
export const PRODUCTS_GET_ALL_FILTER_R = 'PRODUCTS_GET_ALL_FILTER_R'

export const PRODUCTS_SET_FILTER = 'PRODUCTS_SET_FILTER'
export const PRODUCTS_SET_ORDER = 'PRODUCTS_SET_ORDER'
export const PRODUCTS_RESET_FILTER = 'PRODUCTS_RESET_FILTER'
